### ISSUE TITLE
[Request] Suppress output of correct words

### ISSUE THREAD

**Issue by ian-james** [keeferrourke/lang_tools#1]
Command line argument  that reduces output so that only suggestions and incorrect words are passed back in Json.

LangTools I believe returns correct words at the top.

**Comment by keeferrourke** [comment]
Sure thing!

**Comment by keeferrourke** [comment]
Updated `spell_check.py` to suppress correctly spelled words by default. To reveal the list of correct words, run with either the `-c` or `--correct` options.

This behaviour is probably preferable for a general purpose spell checker, however if used in conjunction with analytics, revealing a list of correctly spelled words may be useful for some statistical analysis.
