### ISSUE TITLE
IFS JSON keys

### ISSUE THREAD

**Issue by ian-james** [keeferrourke/lang_tools#2]
Feature request for different JSON key tags specifically for the IFS.

For future use, once decided upon,  perhaps there could be a command line option to select IFS keys instead of the default tags used by the tools. 
For instance if langTool return has the JSON variable 'xpos': 10,

It would be good if that could be translated into a more IFS friendly version to reduce internal parsing:
ex) 'characterPos': 10

**Comment by keeferrourke** [comment]
Are you just asking for me to rename some of the JSON variables? Or would be it better for the lang tools to work in terms of words/line instead of x-char, y-line offsets?

For instance, given input:
```
This is a sentance.*
This is a sentence.
```
Rather than highlighting a spelling mistake at `x:12` chars in with `y:0` line offset, would it be better for the scripts to do a little more processing and determine the mistake is on `line:1` at `word: 4`?

Let me know!

**Comment by keeferrourke** [comment]
in commit 8aeb3b4, I've changed the JSON keys `fromx` and `fromy` to `char` and `line` respectively; I also noticed a few off-by-one errors in the offsets, which have now been corrected.

I hope that this sufficiently addresses this issue? let me know!

**Comment by ian-james** [comment]
Yeah, I'm just asking for a small change of  json tags names. The example you mentioned is char and line are definitely better than x and y.  The names of the tags are just something to keep as consistent as we can between all tools. 

When I hacked this tool into the IFS feedback system I used the following, which includes a couple of hardcode IFS json tags like toolname and type.

```
json_string += '"feedback": [\n'
    for i in range(len(misspelled)):
        json_string += '{\n'
        json_string += '"target":"' + str(misspelled[i][2][0]) + '",\n' 
        json_string += '"wordNum": ' + str(misspelled[i][1]) + ',\n'
        json_string += '"lineNum": ' + str(misspelled[i][0]) + ',\n'
        json_string += '"type": "spelling",\n'
        json_string += '"toolName": "hunspell",\n'
        json_string += '"filename": "' + str(filename) + '",\n'
        json_string += '"feedback": "Selected word not found in dictionary",\n'
        j_array = json.dumps(misspelled[i][2][1])
        json_string += '"suggestions": ' + j_array + '\n'
        json_string += '}'
        if i != (len(misspelled) - 1):
            json_string +=','
        json_string += '\n'
    json_string += ']\n'
    json_string += '}\n'
```

**Comment by keeferrourke** [comment]
Just a note, the script *does* return a char position for a misspelled word, not a word position. I could hack a word position into the tool, but now that I think of it, it might be better if word boundaries are determined elsewhere (I assume this would only be useful for the purpose of highlighting things in the GUI).

**Comment by ian-james** [comment]
I could see the char position being more (or at least) as helpful than the word position that hunspell provides. I'll have to take a look back at how the GUI regex works. We will want to be consistent on this and having all three line, char and word won't hurt anything.

I'll take another look this in a bit.

**Comment by keeferrourke** [comment]
Alright, let me know :+1:

**Comment by ian-james** [comment]
Alright, I changed the integrated version of spell_checker to calculate two extra variables 
linePos which is the position on that line
charPos which is position the character position from the start of the file

I was thinking grammar.py already uses charPos (?!) which if it does works quite a bit better with the IFS now in terms of search and replace speed.

**Comment by keeferrourke** [comment]
@ian-james `grammar.py` uses x / y offsets, so I have it returning the line number from the beginning of the file (where the first line of text is `line: 1` calculated from the y-offset of 0), and the character position *on each line*. This can best be thought of rows and columns in terminal applications. 

`spell_check.py` uses word / line counts; again the word count resets for each line. If the word count indication isn't useful, I can remove it from the JSON output and replace it with a char/line offset to match `grammar.py`

If your integrated version of `spell_check.py` calculates charPos from the beginning of the file, it might be a good idea to change it to charPos from the beginning of the line for consistency. We can discuss this in our meeting this afternoon?

I'll update my version of `spell_check.py` from yours and make some revisions today, as well as address the other outstanding issues.

**Comment by keeferrourke** [comment]
@ian-james the scripts should be much more IFS friendly now; I had to omit some of the "required" keys  (re: [IFS Wiki](https://github.com/ian-james/IFS/wiki/Creating-tools#writing-mandatory-tags)) for the grammar checker, but I think that the output it creates should be extremely useful for identifying where highlighting of an error starts and stops.

Example JSON feedback objects are now outlined in the README [here](https://github.com/keeferrourke/lang_tools/#output).

I mentioned it in the email I sent you recently, but I'm going to attempt to integrate the new versions of the tools in the `dev` branch of IFS.
