### ISSUE TITLE
Option to write json to console

### ISSUE THREAD

**Issue by ian-james** [keeferrourke/lang_tools#4]
If there was an option to write JSON to the command line that would be helpful.

Perhaps there could be an out file flag that indicates when writing to file could occur.

**Comment by keeferrourke** [comment]
I'll restructure the options and usage. I'm thinking that `-v` or `--verbose` used in conjunction with a better named `-o` or `--outfile` flag should print the json both to the specified file and to the console. Though honestly, I'm not sure how useful printing json to the console is, when you could just `cat out.json`.

Thoughts?

**Comment by ian-james** [comment]
The benefit right now of json to the console is that the IFS spawns or exec a job request and passes it down the pipeline to a job queue, which runs the  single command and captures the output directly passing the output back at a later point. Having a second command to call cat out.json would require the IFS to pass both commands every time it.

Perhaps at some point the IFS  will read tool json files, but for now everything is stderr/stdin based.

It's your choice about selecting the flags, I think the idea of separating the output format versus the output location is useful though.

**Comment by keeferrourke** [comment]
Noted. Will do.

**Comment by ian-james** [comment]
BTW, I've hacked spell_check.py into IFS, so if you want to see at a rough level what works.
As you've mentioned you'll want to handle command arguments better than I have for this example.

https://github.com/ian-james/IFS/blob/master/ifs/tools/languageTools/spell_check.py

In termFreq.py, I consider the option of decorating the data for IFS, from the 'decorator pattern'.

**Comment by keeferrourke** [comment]
Refactored versions of both tools now include much more control over the possible outputs. By default, the tools spit JSON to `stdout` and only include information that is relevant to most use cases for each tools. Output can be changed with various flags to each tool (both work extremely similarly).

I've left the English output in both tools, as that output may be easier to read and more useful to debugging for some edge-case where stuff breaks (who knows ¯\\\_(ツ)_/¯). As far as I know though, nothing with respect to these tools on their own should break :smile:
